cve-feed: install request via apt package python3-requests
On more modern debian installs (that kubernetes/test-infra#37909 should bring
to the cve feed job), if you try to install pip3 and then install a dependency
system wide you get that error message:

	error: externally-managed-environment

	× This environment is externally managed
	╰─> To install Python packages system-wide, try apt install
	    python3-xyz, where xyz is the package you are trying to
	    install.

	    If you wish to install a non-Debian-packaged Python package,
	    create a virtual environment using python3 -m venv path/to/venv.
	    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
	    sure you have python3-full installed.

	    If you wish to install a non-Debian packaged Python application,
	    it may be easiest to use pipx install xyz, which will manage a
	    virtual environment for you. Make sure you have pipx installed.

	    See /usr/share/doc/python3.11/README.venv for more information.

	note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
	hint: See PEP 668 for the detailed specification.

Since I'm no python expert, I guess we could have a virtual env but let's just
comply for now on that message since it fixes the situation for our immediate
use case.